//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportPlayer
    {
        public string Id { get; set; }
        public string Position { get; set; }
        public string First_Name { get; set; }
        public string Nickname { get; set; }
        public string Last_Name { get; set; }
        public string FPPG { get; set; }
        public string Played { get; set; }
        public string Salary { get; set; }
        public string Game { get; set; }
        public string Team { get; set; }
        public string Opponent { get; set; }
        public string Injury_Indicator { get; set; }
        public string Injury_Details { get; set; }
    }
}
