//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineup
    {
        public int LineupID { get; set; }
        public int Player1 { get; set; }
        public int Player2 { get; set; }
        public int Player3 { get; set; }
        public int Player4 { get; set; }
        public int Player5 { get; set; }
        public int Player6 { get; set; }
        public int Player7 { get; set; }
        public int Player8 { get; set; }
        public int Player9 { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player10 { get; set; }
        public virtual Player Player11 { get; set; }
        public virtual Player Player12 { get; set; }
        public virtual Player Player13 { get; set; }
        public virtual Player Player14 { get; set; }
        public virtual Player Player15 { get; set; }
        public virtual Player Player16 { get; set; }
        public virtual Player Player17 { get; set; }
    }
}
